### ISSUE TITLE
items that stack above 64 split into stack of at least 64 when in the player inventories

### ISSUE THREAD

**Issue by Nathan22211** [dexman545/Iguana-in-a-Blanket#2]
I tested this when I was in creative mode. slabs and planks seem to be affected by this

**Comment by dexman545** [comment]
Vanilla inventories hard code the max slot stack size to 64, so while you can have stacks above that limit the slots have their own cap. I *might* look into changing this, but there is no good way as modded inventories would also most likely have this limit as well (there's also issues with sending the inventory data to players and saving it. Changing it isn't entirely safe)

**Comment by Nathan22211** [comment]
yeah because the default config ends up allowing stacks above 64 to be pulled out of creative

**Comment by dexman545** [comment]
Patched for 1.0.1
