### ISSUE TITLE
Server unable to boot after the mod is installed and rebooted.

### ISSUE THREAD

**Issue by Neubulae** [dexman545/Iguana-in-a-Blanket#3]
https://pastebin.com/c5cf5EMF

**Comment by Neubulae** [comment]
Should I provide my config? It wasn't like that before I edited the config.

**Comment by Neubulae** [comment]
[iguana.txt](https://github.com/dexman545/Iguana-in-a-Blanket/files/4227456/iguana.txt)
renamed to txt so I could upload it here

**Comment by dexman545** [comment]
Do not set defaultMaxEntity weight to 0, it must be at least 1. If you do not want weight mechanics do not set any weights in the lua config.

**Comment by Neubulae** [comment]
> Do not set defaultMaxEntity weight to 0, it must be at least 1. If you do not want weight mechanics do not set any weights in the lua config.

I set it to 200 and the problem persists

**Comment by Neubulae** [comment]
> Do not set defaultMaxEntity weight to 0, it must be at least 1. If you do not want weight mechanics do not set any weights in the lua config.

I set susceptibility to 0 and the problem happens, it seems like most values don't like to be set to 0.

**Comment by dexman545** [comment]
1.0.1 fixes this
