### ISSUE TITLE
i walk slow

### ISSUE THREAD

**Issue by mikeatike** [dexman545/Iguana-in-a-Blanket#6]
I  need help when i put this in my mod pack and started the game I just slowed down for no reason!!! (I move slower:( )
I tried every thing but what i ended up with is a face full of tears.and then i uninstalled it, now I cant get it back and im still slow

**Comment by dexman545** [comment]
Do you have any items in your inventory?

**Comment by mikeatike** [comment]
yes

**Comment by mikeatike** [comment]
but i deleted it 
and cant get it back

**Comment by mikeatike** [comment]
i dont know whats wrong.

**Comment by jearmstrong21** [comment]
Isn't that exactly what this mod is supposed to do?

**Comment by dexman545** [comment]
Iguana implements a weight system. Items have weight, so the more you carry the more you'll slow down. You'll also move slower when injured.
You remain walking slow when removing iguana as vanilla does not remove the modification to player speed.

**Comment by mikeatike** [comment]
how do i change it :(...

**Comment by mikeatike** [comment]
do i delete a config file?

**Comment by dexman545** [comment]
Open default.lua and set iceWeight to 0

**Comment by mikeatike** [comment]
im sorry but i couldn't find default.lua or ice weight

**Comment by dexman545** [comment]
In iguana.cfg, set `luaConfig` to something.lua
Then in the iguana-blanket folder, duplicate default.lua, rename it to something.lua and set iceWeight to 0

**Comment by mikeatike** [comment]
![pls](https://user-images.githubusercontent.com/63436230/79524213-c91c5580-8014-11ea-88d0-d7cdd4174172.PNG)

![help](https://user-images.githubusercontent.com/63436230/79524263-ea7d4180-8014-11ea-9769-ab8071948a51.PNG)

**Comment by valoeghese** [comment]
that's the jar file, not the config file

**Comment by TelepathicGrunt** [comment]
Open your file explorer. Type in %appdata% and then click minecraft. Now you're in minecraft's folder. Find a folder called "Config" and in it, you can find the configs

You can also use the search bar for the file explorer while you in the minecraft folder to find the files/folders he is talking about

**Comment by mikeatike** [comment]
wait i think its be cause im using a mod launcher called multi mc is that the problem if so then im really sorry  [https://multimc.org/](url)

**Comment by dexman545** [comment]
MultiMC is not the issue. In the folder that the mods folder is in, there is a config folder. What you're looking for is there.

**Comment by mikeatike** [comment]
thanks i fixed it

**Comment by mikeatike** [comment]
god bless you
